# -*- coding: utf-8 -*-
"""ProblemStat_Tredence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WhYJHYpkZScVChCLqKbbCLssSTkb7-q

**STEP 0: Setup Environment**

*   Install required libraries
"""

pip install torch torchvision matplotlib

"""**STEP 1: Dataset (NO manual download needed)**"""

import torch
import torchvision
import torchvision.transforms as transforms

# Transform (normalize images)
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),
                         (0.5, 0.5, 0.5))
])

# Download training data
trainset = torchvision.datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,   # automatic download
    transform=transform
)

trainloader = torch.utils.data.DataLoader(
    trainset, batch_size=64, shuffle=True
)

# Download test data
testset = torchvision.datasets.CIFAR10(
    root='./data',
    train=False,
    download=True,
    transform=transform
)

testloader = torch.utils.data.DataLoader(
    testset, batch_size=64, shuffle=False
)

"""**STEP 2: Create Prunable Linear Layer**"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super(PrunableLinear, self).__init__()

        self.in_features = in_features
        self.out_features = out_features

        # 🔹 1. Weight parameter (same as nn.Linear)
        self.weight = nn.Parameter(
            torch.randn(out_features, in_features) * 0.01
        )

        # 🔹 2. Bias parameter
        self.bias = nn.Parameter(
            torch.zeros(out_features)
        )

        # 🔹 3. Gate scores (LEARNABLE)
        # same shape as weight
        self.gate_scores = nn.Parameter(
            torch.randn(out_features, in_features)
        )

    def forward(self, x):
        # 🔹 Step 1: Convert scores → gates (0 to 1)
        gates = torch.sigmoid(self.gate_scores)

        # 🔹 Step 2: Apply pruning
        pruned_weights = self.weight * gates

        # 🔹 Step 3: Linear transformation
        output = F.linear(x, pruned_weights, self.bias)

        return output

"""**STEP 3: Build Neural Network**"""

class PrunableNet(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = PrunableLinear(32*32*3, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)  # flatten

        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x

"""**STEP 4: Sparsity Loss**"""

def sparsity_loss(model):
    loss = 0
    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates = torch.sigmoid(module.gate_scores)
            loss += torch.sum(gates)  # L1 norm
    return loss

"""**STEP 5: Training Loop**"""

import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = PrunableNet().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

lambda_val = 1e-4   # try different values later

epochs = 10

for epoch in range(epochs):
    running_loss = 0

    for inputs, labels in trainloader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()

        outputs = model(inputs)

        # classification loss
        loss1 = criterion(outputs, labels)

        # sparsity loss
        loss2 = sparsity_loss(model)

        # total loss
        loss = loss1 + lambda_val * loss2

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.3f}")

"""**STEP 6: Evaluate Accuracy**"""

correct = 0
total = 0

with torch.no_grad():
    for inputs, labels in testloader:
        inputs, labels = inputs.to(device), labels.to(device)

        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print("Test Accuracy:", accuracy)

"""**STEP 7: Calculate Sparsity**"""

def calculate_sparsity(model, threshold=1e-2):
    total = 0
    pruned = 0

    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates = torch.sigmoid(module.gate_scores)

            total += gates.numel()
            pruned += (gates < threshold).sum().item()

    return 100 * pruned / total


sparsity = calculate_sparsity(model)
print("Sparsity (%):", sparsity)

"""**STEP 8: Plot Gate Distribution**"""

import matplotlib.pyplot as plt

all_gates = []

for module in model.modules():
    if isinstance(module, PrunableLinear):
        gates = torch.sigmoid(module.gate_scores).detach().cpu().numpy()
        all_gates.extend(gates.flatten())

plt.hist(all_gates, bins=50)
plt.title("Gate Value Distribution")
plt.xlabel("Gate Value")
plt.ylabel("Frequency")
plt.show()